Add 'maintenance' to keywords to check stonith rsc is in maintenance
Newer versions of crmsh can be reporting that the stonith-sbd resource
is in maintenance by the `maintenance` keyword instead of `unmanaged`:

```
TEST: verify_stonith_in_maintenance
INFO: ssh command [crm status | grep stonith-sbd] got output [  * stonith-sbd   (stonith:external/sbd):  Started hawk-node01 (maintenance)] and error []
ERROR: stonith-sbd is not unmanaged but should be
```

This commit adds `maintenance` so the test checks for both.